openapi: 3.0.0
info:
  title: Steam Inventory API
  version: 1.0.0
  description: API для взаимодействия с инвентарём Steam.
paths:
  /inventory/{steamid}/{appid}/{contextid}:
    get:
      summary: "Получение содержимого инвентаря"
      parameters:
        - name: steamid
          in: path
          required: true
          schema:
            type: string
          description: "Идентификатор пользователя."
        - name: appid
          in: path
          required: true
          schema:
            type: integer
          description: "ID приложения (например, 730)."
        - name: contextid
          in: path
          required: true
          schema:
            type: integer
          description: "ID контекста инвентаря."
        - name: l
          in: query
          required: false
          schema:
            type: string
          description: "Язык интерфейса (например, russian)."
        - name: count
          in: query
          required: false
          schema:
            type: integer
          description: "Количество возвращаемых предметов."
      responses:
        '200':
          description: "Содержимое инвентаря успешно получено"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  items:
                    type: array
                    items:
                      type: object
        default:
          description: "Ошибка при получении инвентаря"
